# loads the extension always
# useful for defining changes and overides to the default behaviour
# eg env,ui,functions
# all file names in the extensions folder
AUTO_LOADED_EXTENSIONS: 
PRETTY_PRINT: true                # whether to show colors when printing ouput
EDITOR: nvim
PREFERRED_SELECTOR: fzf           # fzf, rofi
VIDEO_QUALITY: 1080               # the quality of the video when streaming with a player other than mpv
ENABLE_PREVIEW: true
IMAGE_RENDERER: chafa             # what to use for rendering images in the terminal [chafa/icat]
DISOWN_STREAMING_PROCESS: true    # whether to run mpv as a background process and prevent it from closing even if you terminate the program or terminal session
UPDATE_RECENT: true               # whether to update the recent list kept locally [true/false]
SEARCH_HISTORY: true              # whether to update the recent list kept locally [true/false]
NO_OF_RECENT: 30                  # the number of recent videos to keep
PLAYER: mpv                       # the player to use for streaming [mpv/vlc]
PREFERRED_BROWSER: firefox:/home/lunics/usb_copy/homelab/share/browser/zen/lunics   # browser's profile use to extract cookies from, used to by yt-dlp to access content that would require login
NO_OF_SEARCH_RESULTS: 30          # the number of results to get from yt-dlp
NOTIFICATION_DURATION: 5          # the duration notifications stay on the screen
DOWNLOAD_DIRECTORY: /home/lunics/videos/yt-x
UPDATE_CHECK: false
