{ config, ... }:{
  xdg.configFile."hypr/hyprland.conf".text = ''
    exec-once = /etc/polkit-kde-authentication-agent-1
    exec-once = dbus-update-activation-environment --systemd --all
    # needed for firefox screen sharing under wayland and other utilities
    exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
    exec-once = systemctl --user start hyprland.target

  '' + 
    (if config._.status_bar == "waybar" then
      ''exec      = pkill waybar; waybar --log-level error &> /run/user/$(id -u)/waybar.log &''
    else if config._.status_bar == "hyprpanel" then
      ''exec      = pkill hyprpanel; hyprpanel &> /run/user/$(id -u)/hyprpanel.log &''
    else "") + 
  ''

    autogenerated = 0                    # 1 = warning message at startup, 0 = disabled
    debug:disable_logs = false
    
    source = $HOME/.config/hypr/config.d/*
  '';
}
