# all options https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

$font = Monospace

general {
  hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#   fingerprint {
#     enabled = true
#     ready_message = Scan fingerprint to unlock
#     present_message = Scanning...
#     retry_delay = 250 # in milliseconds
#   }
# }

# shape {
#   monitor =
#   size = 360, 60
#   color = rgba(0, 0, 0, 0.0) # no fill
#   rounding = -1 # circle
#   border_size = 4
#   border_color = rgba(0, 207, 230, 1.0)

#   position = 0, 80
#   halign = center
#   valign = center
# }

animations {
  enabled   = true
  bezier    = linear, 1, 1, 0, 0
  animation = fadeIn, 1, 5, linear
  animation = fadeOut, 1, 5, linear
  animation = inputFieldDots, 1, 2, linear
}

background {
  monitor     =
  path        = screenshot
  blur_passes = 1           # from 1 to 50
  brightness  = 0.9         # 90% of the current brightness
  vibrancy    = 0.2
}

input-field {
  monitor =
  # size              = 20%, 5%
  outline_thickness = 3

  inner_color = rgba(0, 0, 0, 0.0) # no fill
  outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
  check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
  font_color = rgb(143, 143, 143)
  fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

  fade_on_empty = false
  rounding = -1            # 15 (default), -1 = circle

  font_family = $font
  placeholder_text =            # Input password...     # message inside the box
  fail_text = $PAMFAIL

  # dots_text_format = *
  dots_spacing = 0.3

  # hide_input = true

  position = 0, -20
  halign = center
  valign = center
}


label {                     # TIME
  monitor     =
  text        = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
  font_size   = 90
  font_family = $font
  position    = -30, 0
  halign      = right
  valign      = top
}


label {                   # DATE
  monitor     =
  text        =           # cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
  font_size   = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

label {                   # LANG
  monitor   =
  text      =             # $LAYOUT[en,ru]
  font_size = 24
  onclick   = hyprctl switchxkblayout all next
  position  = 250, -20
  halign    = center
  valign    = center
}
