#!/usr/bin/env bash

sleep 1

killall xdg-desktop-portal-hyprland 2> /dev/null
# xdg-desktop-portal-gtk 2> /dev/null
killall xdg-desktop-portal 2> /dev/null

sleep 1

/usr/lib/xdg-desktop-portal-hyprland &

sleep 2

/usr/lib/xdg-desktop-portal &
