kind:       HelmChart
apiVersion: helm.cattle.io/v1

metadata:
  name:      argo-cd
  namespace: kube-system

spec:
  repo:            https://argoproj.github.io/argo-helm
  chart:           argo-cd
  version:         9.2.4
  targetNamespace: argo-cd
  createNamespace: true
  valuesContent: |-
    fullnameOverride: argo-cd
