{ config, ... }:{
  wayland.windowManager.hyprland.extraConfig = ''
    exec-once = /etc/polkit-kde-authentication-agent-1

  '' + 
    (if config._.status_bar == "waybar" then
      ''exec      = pkill waybar; waybar --log-level error &> /run/user/$(id -u)/waybar.log &''
    else if config._.status_bar == "hyprpanel" then
      ''exec      = pkill hyprpanel; hyprpanel &> /run/user/$(id -u)/hyprpanel.log &''
    else "") + 
  ''

    autogenerated = 0                    # 1 = warning message at startup, 0 = disabled
    debug:disable_logs = false
  '';
}
