{
  flake.aspects = {
    options.generic = { lib, ... }: with lib; {
      options._.facter-report = mkOption {
        type    = types.nullOr types.path;
        default = null;     # path of the report generated by `sudo nixos-facter -o facter.json`
      };
    };

    # nixos/modules/hardware/facter, already in nixpkgs module-list
    facter.nixos = { config, pkgs, ... }:{
      hardware.facter = {
        # enable defaults to `report != {}`, so it stays off until a report is set
        reportPath = config._.facter-report;
      };

      environment.systemPackages = with pkgs; [
        nixos-facter     # regenerate the report: sudo nixos-facter -o facter.json
      ];
    };
  };
}
